# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_noder_wrappers", use_symbols = TRUE, package_name = "noder")

#' @docType package
#' @usage NULL
#' @useDynLib noder, .registration = TRUE
NULL

#' @export
AcyclicGraph <- new.env(parent = emptyenv())

AcyclicGraph$new <- function(root) .Call(wrap__AcyclicGraph__new, root)

AcyclicGraph$add_node <- function(node) invisible(.Call(wrap__AcyclicGraph__add_node, self, node))

AcyclicGraph$add_child <- function(node, child) invisible(.Call(wrap__AcyclicGraph__add_child, self, node, child))

AcyclicGraph$get_children <- function(node) .Call(wrap__AcyclicGraph__get_children, self, node)

AcyclicGraph$get_parents <- function(node) .Call(wrap__AcyclicGraph__get_parents, self, node)

AcyclicGraph$find_leaves <- function(node) .Call(wrap__AcyclicGraph__find_leaves, self, node)

AcyclicGraph$find_least_common_parents <- function(selected) .Call(wrap__AcyclicGraph__find_least_common_parents, self, selected)

AcyclicGraph$as_list <- function() .Call(wrap__AcyclicGraph__as_list, self)

#' @rdname AcyclicGraph
#' @usage NULL
#' @export
`$.AcyclicGraph` <- function (self, name) { func <- AcyclicGraph[[name]]; environment(func) <- environment(); func }

#' @export
`[[.AcyclicGraph` <- `$.AcyclicGraph`


# nolint end
