# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_orbweaver_wrappers", use_symbols = TRUE, package_name = "orbweaver")

#' @docType package
#' @usage NULL
#' @useDynLib orbweaver, .registration = TRUE
NULL

rs_populate_edges_directed_graph <- function(graph, dataframe, parent_col, child_col) .Call(wrap__rs_populate_edges_directed_graph, graph, dataframe, parent_col, child_col)

rs_populate_nodes_directed_graph <- function(graph, dataframe, node_id_col, data_col) .Call(wrap__rs_populate_nodes_directed_graph, graph, dataframe, node_id_col, data_col)

Node <- new.env(parent = emptyenv())

Node$get_data <- function() .Call(wrap__Node__get_data, self)

Node$set_data <- function(data) invisible(.Call(wrap__Node__set_data, self, data))

#' @export
`$.Node` <- function (self, name) { func <- Node[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Node` <- `$.Node`

DirectedGraph <- new.env(parent = emptyenv())

DirectedGraph$new <- function() .Call(wrap__DirectedGraph__new)

DirectedGraph$add_node <- function(node_id, data) .Call(wrap__DirectedGraph__add_node, self, node_id, data)

DirectedGraph$get_node <- function(node_id) .Call(wrap__DirectedGraph__get_node, self, node_id)

DirectedGraph$get_nodes <- function(ids) .Call(wrap__DirectedGraph__get_nodes, self, ids)

DirectedGraph$add_edge <- function(from, to) .Call(wrap__DirectedGraph__add_edge, self, from, to)

DirectedGraph$add_path <- function(path) .Call(wrap__DirectedGraph__add_path, self, path)

DirectedGraph$edge_exists <- function(from, to) .Call(wrap__DirectedGraph__edge_exists, self, from, to)

DirectedGraph$deep_clone <- function() .Call(wrap__DirectedGraph__deep_clone, self)

DirectedGraph$find_path <- function(from, to) .Call(wrap__DirectedGraph__find_path, self, from, to)

DirectedGraph$children <- function(node) .Call(wrap__DirectedGraph__children, self, node)

DirectedGraph$parents <- function(node) .Call(wrap__DirectedGraph__parents, self, node)

DirectedGraph$remove_edge <- function(from, to) invisible(.Call(wrap__DirectedGraph__remove_edge, self, from, to))

DirectedGraph$remove_node <- function(node_id) invisible(.Call(wrap__DirectedGraph__remove_node, self, node_id))

DirectedGraph$has_parents <- function(node_id) .Call(wrap__DirectedGraph__has_parents, self, node_id)

DirectedGraph$has_children <- function(node_id) .Call(wrap__DirectedGraph__has_children, self, node_id)

DirectedGraph$nodes <- function() .Call(wrap__DirectedGraph__nodes, self)

DirectedGraph$least_common_parents <- function(selected) .Call(wrap__DirectedGraph__least_common_parents, self, selected)

DirectedGraph$get_leaves <- function() .Call(wrap__DirectedGraph__get_leaves, self)

DirectedGraph$get_leaves_under <- function(node_ids) .Call(wrap__DirectedGraph__get_leaves_under, self, node_ids)

DirectedGraph$clear_edges <- function() invisible(.Call(wrap__DirectedGraph__clear_edges, self))

DirectedGraph$into_dag <- function() .Call(wrap__DirectedGraph__into_dag, self)

#' @export
`$.DirectedGraph` <- function (self, name) { func <- DirectedGraph[[name]]; environment(func) <- environment(); func }

#' @export
`[[.DirectedGraph` <- `$.DirectedGraph`

DirectedAcyclicGraph <- new.env(parent = emptyenv())

DirectedAcyclicGraph$get_node <- function(node_id) .Call(wrap__DirectedAcyclicGraph__get_node, self, node_id)

DirectedAcyclicGraph$get_nodes <- function(ids) .Call(wrap__DirectedAcyclicGraph__get_nodes, self, ids)

DirectedAcyclicGraph$edge_exists <- function(from, to) .Call(wrap__DirectedAcyclicGraph__edge_exists, self, from, to)

DirectedAcyclicGraph$deep_clone <- function() .Call(wrap__DirectedAcyclicGraph__deep_clone, self)

DirectedAcyclicGraph$find_path <- function(from, to) .Call(wrap__DirectedAcyclicGraph__find_path, self, from, to)

DirectedAcyclicGraph$children <- function(node) .Call(wrap__DirectedAcyclicGraph__children, self, node)

DirectedAcyclicGraph$parents <- function(node) .Call(wrap__DirectedAcyclicGraph__parents, self, node)

DirectedAcyclicGraph$has_parents <- function(node_id) .Call(wrap__DirectedAcyclicGraph__has_parents, self, node_id)

DirectedAcyclicGraph$has_children <- function(node_id) .Call(wrap__DirectedAcyclicGraph__has_children, self, node_id)

DirectedAcyclicGraph$nodes <- function() .Call(wrap__DirectedAcyclicGraph__nodes, self)

DirectedAcyclicGraph$least_common_parents <- function(selected) .Call(wrap__DirectedAcyclicGraph__least_common_parents, self, selected)

DirectedAcyclicGraph$get_leaves <- function() .Call(wrap__DirectedAcyclicGraph__get_leaves, self)

DirectedAcyclicGraph$get_leaves_under <- function(node_ids) .Call(wrap__DirectedAcyclicGraph__get_leaves_under, self, node_ids)

DirectedAcyclicGraph$into_directed <- function() .Call(wrap__DirectedAcyclicGraph__into_directed, self)

#' @export
`$.DirectedAcyclicGraph` <- function (self, name) { func <- DirectedAcyclicGraph[[name]]; environment(func) <- environment(); func }

#' @export
`[[.DirectedAcyclicGraph` <- `$.DirectedAcyclicGraph`


# nolint end
